title: "Niclas Knecht's personal website"
author: "Niclas Knecht"
description: "This is my personal website."

email: "hopper_wobbles2p@icloud.com"
linkedin_url: "https://www.linkedin.com/in/niclas-knecht/"
github_url: "https://github.com/NiclasKnecht"

email-subject:
  en: "Hello, Niclas!"
  de: "Hallo, Niclas!"

cvs:
  en: "2026-10-03 CV_Niclas_Knecht.pdf"
  de: 

portrait: "portrait.jpg"





collections:
  content:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_content"
      type: content
    values:
      layout: pages
      lang: en
  - scope:
      path: "_content/de"
      type: content
    values:
      layout: pages
      lang: de

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-polyglot