title: "Niclas Knecht"
description: "This is my personal website."


email: "nk_admin@icloud.com"
linkedin: "https://www.linkedin.com/in/niclas-knecht/"
github: "https://github.com/NiclasKnecht"

summary: " "
