title: Niclas Knecht
description: Personal website of Niclas Knecht
author: Niclas Knecht
url: "https://username.github.io"
email: your.address@example.com
linkedin_url: "https://www.linkedin.com/in/..."
github_url: "https://github.com/..."
portrait: "portrait.jpg"

email_subject:
  en: "Hello Niclas!"
  de: "Hallo Niclas!"

cvs:
  en: "2026-10-08 CV_Niclas_Knecht.pdf"
  de: "2026-10-08 Lebenslauf_Niclas_Knecht.pdf"
cv_size: "115 KB"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  content:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_content"
      type: content
    values:
      layout: pages
      lang: en
  - scope:
      path: "_content/de"
      type: content
    values:
      layout: pages
      lang: de