baseURL: "https://mathildecol.github.io"
title: Niclas Knecht
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: CV
          url: /cv/
          weight: 2

params:
    description: "I am a PhD student at the Bordeaux School of Economics under the supervision of Olivier Bargain. I am interested in the intersection of economics and psychology."
    author: Niclas Knecht
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title : Niclas Knecht
          subtitle: "I am a PhD student at the [Bordeaux School of Economics](https://www.bse.u-bordeaux.fr/) under the supervision of [Olivier Bargain](https://sites.google.com/site/bargainoliv/). I am interested in the intersection of economics and psychology."
          imageUrl: "/picture.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Niclas Knecht
          buttons:
            - name: Research
              url: /research/
            - name: CV
              url: /cv/CV_NK_Autumn2023.pdf
    socialIcons:
        - name: Email
          url: mailto:niclas.knecht@u-bordeaux.fr
        - name: LinkedIn
          url: https://www.linkedin.com/in/niclas-knecht/
        #- name: GitHub
        #  url: https://github.com/colmate
        - name: Location
          url: /location/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Mathilde Col"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
